# app/config/security.yml

security:
    encoders:
            App\Entity\User:
                algorithm: bcrypt
                cost: 12
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       our_db_provider:
                   entity:
                       class: App\Entity\User
                       property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/
            anonymous:    true
            form_login:
              login_path: login
              check_path: login_check
            logout:
              path:       logout
              target:     login
            provider: our_db_provider


    access_control:
        # require ROLE_ADMIN for /admin*
         - { path: ^/user/space, roles: ROLE_USER }
         - { path: ^/admin/space, roles: ROLE_SUPER_ADMIN }